version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: transaction-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: transaction_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/migrations:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transaction-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: transaction_db

volumes:
  mysql-data:
